### GET

GET localhost:8888/v1/session
Authorization: test_mode853250161915985958testmode
### GET
GET localhost:8888/v1/settings/debug
Authorization: test_mode853250161915985958testmode
### GET

GET localhost:8888/v1/data/links
Authorization: 853250161915985958

###
GET localhost:8888/v1/data/token_features

### Test voting
POST localhost:8888/voting/topgg
Authorization: topgg
Content-Type: application/json

{
  "user": "214347948316819456"
}

### Test voting
POST localhost:8888/voting/botlistme
Authorization: botlistme
Content-Type: application/json

{
  "user": "214347948316819456"
}
### Test voting
POST localhost:8888/voting/discordbotlistcom
Authorization: discordbotlistcom
Content-Type: application/json

{
  "id": "214347948316819456"
}
