version: '3.1'
services:
  pgdatabase:
    image: postgres:14.4
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_DB: "postgres"
    volumes:
      - database:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  database:

