version: '3.7'

services:
  app:
    image: chojo/reputation-bot:latest
    networks:
      - repbot
    depends_on:
      - database
    volumes:
      - ${PWD}/config/:/config/
  database:
    networks:
      - repbot
    image: postgres:13.2
    volumes:
    - db_data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_DB: "repbot"

networks:
  repbot:
    name: repbot
    external: false

volumes:
  db_data:
