name: Verify state

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Build with Gradle
        run: ./gradlew --build-cache build
      - name: Test with Gradle
        run: ./gradlew test --info

  enforce-encoding:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Remove allowed us-ascii files before check
        run: rm src/main/resources/locale.properties src/main/resources/locale_en_US.properties # This needs improvement
      - name: Check UTF-8 for resource bundles
        run: |
          find src/main/resources/locale* -type f -exec file --mime {} \; | grep -v charset=utf-8 && NOT_UTF_FOUND=1 || true
          [[ \"$NOT_UTF_FOUND\" == \"1\" ]] && exit 1 || true
